<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>dai</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~D</string>
	<key>name</key>
	<string>Daisy setup file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.daisy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.daisy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.semicolon.daisy</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.daisy</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.daisy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b(?i:(def\w+))\b)(\s+)((\w|\-|\!|\?)*)</string>
			<key>name</key>
			<string>meta.function.daisy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.daisy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#|\?)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.daisy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.daisy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.daisy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\*)(\S*)(\*)</string>
			<key>name</key>
			<string>variable.other.global.daisy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:case|do|let|loop|if|else|when)\b</string>
			<key>name</key>
			<string>keyword.control.daisy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:eq|neq|and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.daisy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:null|nil)\b</string>
			<key>name</key>
			<string>constant.language.daisy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![-\w])(?i:cons|car|cdr|cond|lambda|format|setq|setf|quote|eval|append|list|listp|memberp|t|load|progn)(?![-\w])</string>
			<key>name</key>
			<string>support.function.daisy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.daisy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.daisy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.daisy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.daisy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.daisy</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.daisy</string>
	<key>uuid</key>
	<string>E82F9010-B5B4-4788-91B3-5898C75A0D6C</string>
</dict>
</plist>
